# Generated by Django 4.1.7 on 2023-03-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='dec',
            new_name='desc',
        ),
    ]
